/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.tools.plugin;

/**
 *
 * @author purplebleed
 */
public class EyedropperPanel extends javax.swing.JPanel {

    /**
     * Creates new form EyedropperPanel
     */
    public EyedropperPanel() {
        initComponents();
    }

    public void setStatusLabel(String message) {
        statusLabel.setText(message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();

        statusLabel.setFont(statusLabel.getFont().deriveFont((float)10));
        statusLabel.setText(org.openide.util.NbBundle.getMessage(EyedropperPanel.class, "EyedropperPanel.statusLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
